print("Welcome to the tip calculator.")
total = float(input("What was the total bill?"))
tip = float(input("What percentage tip would you like to give? 10, 12, or 15?"))
people = float(input("How many people to split the bill?"))
total = total + ((tip*total) / 100)
total = round(total / people, 2)
print(f"Each person should pay: ${total}")
